In [2]:
# Importing required libraries

import pandas as pd
from pandas.io.json import json_normalize
import warnings
warnings.filterwarnings("ignore")

In [3]:
# Read JSON file containing tweets data and removce tweets not in English

raw_tweets = pd.read_json(r'farmers-protest-tweets-2021-03-5.json', lines=True)
raw_tweets = raw_tweets[raw_tweets['lang']=='en']

# Normalize 'user' field

users = json_normalize(raw_tweets['user'])
users.drop(['description', 'linkTcourl'], axis=1, inplace=True)
users.rename(columns={'id':'userId', 'url':'profileUrl'}, inplace=True)
users.head(5)

# Create DataFrame and remove duplicates

users = pd.DataFrame(users)
users.drop_duplicates(subset=['userId'], inplace=True)

Shape:  (417511, 21)

,url,date,content,renderedContent,id,user,outlinks,tcooutlinks,replyCount,retweetCount,...,quoteCount,conversationId,lang,source,sourceUrl,sourceLabel,media,retweetedTweet,quotedTweet,mentionedUsers
0,https://twitter.com/ShashiRajbhar6/status/1376...,2021-03-30 03:33:46+00:00,Support ðŸ‘‡\n\n#FarmersProtest,Support ðŸ‘‡\n\n#FarmersProtest,1376739399593910273,"{'username': 'ShashiRajbhar6', 'displayname': ...",[],[],0,0,...,0,1376739399593910273,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None
1,https://twitter.com/kaursuk06272818/status/137...,2021-03-30 03:33:23+00:00,Supporting farmers means supporting our countr...,Supporting farmers means supporting our countr...,1376739306287427584,"{'username': 'kaursuk06272818', 'displayname':...",[],[],0,0,...,0,1376739306287427584,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,[{'previewUrl': 'https://pbs.twimg.com/media/E...,NaN,None,None
2,https://twitter.com/kaursuk06272818/status/137...,2021-03-30 03:31:00+00:00,Support farmers if you are related to food #St...,Support farmers if you are related to food #St...,1376738704128020488,"{'username': 'kaursuk06272818', 'displayname':...",[],[],0,0,...,0,1376738704128020488,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,[{'previewUrl': 'https://pbs.twimg.com/media/E...,NaN,None,None
3,https://twitter.com/SukhdevSingh_/status/13767...,2021-03-30 03:30:45+00:00,#StopHateAgainstFarmers support #FarmersProtes...,#StopHateAgainstFarmers support #FarmersProtes...,1376738640542400518,"{'username': 'SukhdevSingh_', 'displayname': '...",[],[],0,1,...,0,1376738640542400518,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None
4,https://twitter.com/Davidmu66668113/status/137...,2021-03-30 03:30:30+00:00,"You hate farmers I hate you, \nif you love the...","You hate farmers I hate you, \nif you love the...",1376738579171344386,"{'username': 'Davidmu66668113', 'displayname':...",[],[],0,0,...,0,1376738579171344386,en,"<a href=""http://twitter.com/download/android"" ...",http://twitter.com/download/android,Twitter for Android,None,NaN,None,None

In [28]:
def most_retweeted_tweets(df):
    df = df.nlargest(10, 'retweetCount')
    return df[['url', 'user', 'retweetCount']]

most_retweeted_tweets(raw_tweets)

,url,user,retweetCount
408128,https://twitter.com/rihanna/status/13566258896...,"{'username': 'rihanna', 'displayname': 'Rihann...",315547
395142,https://twitter.com/GretaThunberg/status/13566...,"{'username': 'GretaThunberg', 'displayname': '...",103957
266196,https://twitter.com/GretaThunberg/status/13572...,"{'username': 'GretaThunberg', 'displayname': '...",67694
366579,https://twitter.com/miakhalifa/status/13568483...,"{'username': 'miakhalifa', 'displayname': 'Mia...",35921
372793,https://twitter.com/miakhalifa/status/13568277...,"{'username': 'miakhalifa', 'displayname': 'Mia...",26972
314192,https://twitter.com/TeamJuJu/status/1357048037...,"{'username': 'TeamJuJu', 'displayname': 'JuJu ...",23251
215034,https://twitter.com/BobBlackman/status/1357755...,"{'username': 'BobBlackman', 'displayname': 'Bo...",20132
398011,https://twitter.com/vanessa_vash/status/135668...,"{'username': 'vanessa_vash', 'displayname': 'V...",18744
325261,https://twitter.com/kylekuzma/status/135700972...,"{'username': 'kylekuzma', 'displayname': 'kuz'...",17368
163689,https://twitter.com/AmandaCerny/status/1359013...,"{'username': 'AmandaCerny', 'displayname': 'Am...",15677

In [20]:
def top_users(user_df):
    user_df = user_df.nlargest(10, 'statusesCount')
    return user_df[['username', 'userId', 'statusesCount']]

Shape:  (93223, 19)

               username              userId  statusesCount
99351   threadreaderapp  895814938995957760        1762327
271401  GeorgekurianINC          2359140223        1711890
45702    CyberAnonymous           128334973        1435641
143837      unbiased100           238278490        1027493
264418      pavan_sethi           357267251        1015822
150833      animesh1977            15936294         974774
172413     CNBCTV18Live            44839509         944140
1392           htTweets            36327407         867921
234155        CNNnews18             6509832         863748
9547         IndiaToday            19897138         851081

In [49]:
def top_days(df):
    df = df.groupby(['date']).size().reset_index(name='Counts')
    df = df.nlargest(10, 'Counts')
    return df

         date  Counts
2  2021-02-03   83403
3  2021-02-04   58300
4  2021-02-05   33165
1  2021-02-02   28440
5  2021-02-06   22298
6  2021-02-07   11244
8  2021-02-09    9269
7  2021-02-08    8863
9  2021-02-10    7938
10 2021-02-11    5668